name: simple_chat_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  fluent_ui: ^4.10.0
  flutter_acrylic: ^1.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  intl: ^0.20.2
  logging: ^1.3.0
  uuid: ^4.5.1
  win32: ^5.10.1
  window_manager: ^0.4.3
  system_theme: ^3.1.2

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
